version: '3.1'

services:
  wordpress:
    image: wordpress:cli-php8.1
    restart: always
#    build:
#      context: ./docker
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
    command: |
      apt-get update
      apt-get install wget
      wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
      chmod +x phpunit
      ./phpunit --version
      tail -F /var/www/html/index.php #prevent container restarts @todo tail a txt file
#    tty: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
