# This is an workflow to autmaticly tests the validity of your OAS definitons and the Common Gateway's abillity to provide an API for them

name: Automated Testing

on:
  pull_request:
    branches:
      - master
      - staging
      - development
      - acceptance

  push:
    branches:
      - master
      - staging
      - development
      - acceptance


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1


      # Prepare voor docker test
#      - name: Create vendor folder
#        run: |
#          mkdir api/vendor
#          chmod +777 api/vendor
#          chmod +777 -R api/public
#      - name: Build the Docker image
#        run: docker compose build -f docker-compose-cli.yml
      - name: Build and Run the docker image
        run: docker compose -f docker-compose-cli.yml up -d --build
      - name: Taking some sleep (for containers to come up)
        run: sleep 10
      - name: Check if all containers are running
        run: docker ps
      - name: Dumping the logs
        run: docker compose logs
      - name: Install security with snyk
        run: |
          sudo  mkdir -p ~/.docker/cli-plugins && ssudo \ curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan &&\
          sudo chmod +x ~/.docker/cli-plugins/docker-scan
#        run: sudo apt-get update && sudo apt-get install docker-scan-plugin
      - name: Check container security with snyk
        run:  docker scan wordpress
      - name: List al the plugins
        run: docker compose -f docker-compose-cli.yml exec wordpress wp plugin list
      - name: Activate the plugin
        run: docker compose -f docker-compose-cli.yml exec wordpress wp plugin activate OpenPub
      - name: Chores
        if: (success() || failure())
        run: docker compose -f docker-compose-cli.yml down
  publish:
    # Lets make sure we only publish afther an succeful build
    needs: build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Let create an artifact for our plugin
    steps:
      - uses: actions/checkout@v3
      - uses: vimtor/action-zip@v1
        with:
          files: plugins/OpenPub
          dest: OpenPub.zip
      - uses: actions/upload-artifact@v1
        with:
          name: OpenPub
          path: ${{ github.workspace }}/OpenPub.zip