# This is an workflow to autmaticly tests the validity of your OAS definitons and the Common Gateway's abillity to provide an API for them

name: Automated Testing

on:
  pull_request:
    branches:
      - master
      - staging
      - development
      - acceptance

  push:
    branches:
      - master
      - staging
      - development
      - acceptance


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1


      # Prepare voor docker test
#      - name: Create vendor folder
#        run: |
#          mkdir api/vendor
#          chmod +777 api/vendor
#          chmod +777 -R api/public
#      - name: Build the Docker image
#        run: docker compose build -f docker-compose-cli.yml
      - name: Build and Run the docker image
        run: docker-compose up --build -d -f docker-compose-cli.yml
      - name: Taking some sleep (for containers to come up)
        run: sleep 45
      - name: Check if all containers are running
        run: docker ps
      - name: Dumping the logs
        run: docker compose logs
      - name: Check container security with snyk
        run: docker compose logs
      - name: Chores
        if: (success() || failure())
        run: docker compose down
    publish:
      - uses: vimtor/action-zip@v1
        with:
          files: plugins/OpenPub
          recursive: false
          dest: OpenPub.zip
